/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projnnn;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author alool
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(new java.awt.Color(255, 102, 255));
        jButton11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Rep.(A,P&D)");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 180, 40));

        jButton9.setBackground(new java.awt.Color(255, 102, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Rep.(P&I)");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, 180, 40));

        jButton14.setBackground(new java.awt.Color(255, 153, 153));
        jButton14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("← Back");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, 40));

        jButton8.setBackground(new java.awt.Color(51, 255, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Show_Information");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 310, 70));

        jButton7.setBackground(new java.awt.Color(51, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\alool\\Documents\\NetBeansProjects\\Projnnn\\src\\main\\java\\com\\mycompany\\projnnn\\software-engineer (1).png")); // NOI18N
        jButton7.setToolTipText("Add_Admin");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 120, 110));

        jButton6.setBackground(new java.awt.Color(51, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\alool\\Documents\\NetBeansProjects\\Projnnn\\src\\main\\java\\com\\mycompany\\projnnn\\invoice (2) (1).png")); // NOI18N
        jButton6.setToolTipText("Add_Invoice");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 180, 120));

        jButton5.setBackground(new java.awt.Color(51, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\alool\\Documents\\NetBeansProjects\\Projnnn\\src\\main\\java\\com\\mycompany\\projnnn\\medical-symbol (4) (1).png")); // NOI18N
        jButton5.setToolTipText("Add_Medications");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 180, 120));

        jButton4.setBackground(new java.awt.Color(51, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\alool\\Documents\\NetBeansProjects\\Projnnn\\src\\main\\java\\com\\mycompany\\projnnn\\schedule (1).png")); // NOI18N
        jButton4.setToolTipText("Add_Appointment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 180, 120));

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\alool\\Documents\\NetBeansProjects\\Projnnn\\src\\main\\java\\com\\mycompany\\projnnn\\medical (1).png")); // NOI18N
        jButton3.setToolTipText("Add_Patient");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 180, 120));

        jButton2.setBackground(new java.awt.Color(51, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\alool\\Documents\\NetBeansProjects\\Projnnn\\src\\main\\java\\com\\mycompany\\projnnn\\nurse (1) (1).png")); // NOI18N
        jButton2.setToolTipText("Add_Nurse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 120));

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\alool\\Documents\\NetBeansProjects\\Projnnn\\src\\main\\java\\com\\mycompany\\projnnn\\doctor (2).png")); // NOI18N
        jButton1.setText("  ");
        jButton1.setToolTipText("Add_Doctor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 180, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\alool\\Documents\\NetBeansProjects\\Projnnn\\src\\main\\java\\com\\mycompany\\projnnn\\Screenshot 2023-12-08 001809 (1).png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1108, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
 //______________________________________________________________________________________   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         NewJFrameD f1 = new NewJFrameD();  
         f1.setVisible(true);  
         this.dispose();  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NewJFrameNurse f2 = new NewJFrameNurse();
        f2.setVisible(true); 
        this.dispose();  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        NewJFramePatient f3 = new NewJFramePatient();
        f3.setVisible(true); 
        this.dispose();  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         NewJFrameAppointment f4 = new NewJFrameAppointment();
         f4.setVisible(true); 
         this.dispose(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         NewJFrameMedications f5 = new NewJFrameMedications();
         f5.setVisible(true); 
         this.dispose(); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        NewJFrameInvoice f6 = new NewJFrameInvoice();
        f6.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         NewJFrame_AddNewAdmin f7 = new NewJFrame_AddNewAdmin();  
         f7.setVisible(true);  
         this.dispose();  
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
          NewJFrame f8 = new NewJFrame();  
          f8.setVisible(true);  
          this.dispose();   
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       //Show All INFO.
        NewJFrame_Show_All f9 = new NewJFrame_Show_All();
         f9.setVisible(true);  
          this.dispose();   
       
       
       
       
       
       
    }//GEN-LAST:event_jButton8ActionPerformed

    
    
    //Rep. {0}
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

             Connection con;
             InputStream input;
             JasperReport jr;
             JasperDesign jd;
             JasperPrint jp;
             OutputStream output;
        try{
             DriverManager.registerDriver(new org.postgresql.Driver());
             String conninfo = "jdbc:postgresql://localhost:5432/postgres";
             con=DriverManager.getConnection(conninfo,"allii","12345");

             input = new FileInputStream(new File("PI.jrxml"));
             jd = JRXmlLoader.load(input);
             jr = JasperCompileManager.compileReport(jd);
             jp = JasperFillManager.fillReport(jr,null,con);
             output = new FileOutputStream(new File("Invoice.pdf"));
             JasperExportManager.exportReportToPdfStream(jp,output);
             output.close();
             input.close();
             con.close();
             JOptionPane.showMessageDialog(null, "Success !");

        }catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton9ActionPerformed
 
    
    
    //Rep. {2}
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      
        Connection con;
             InputStream input;
             JasperReport jr;
             JasperDesign jd;
             JasperPrint jp;
             OutputStream output;
        try{
             DriverManager.registerDriver(new org.postgresql.Driver());
             String conninfo = "jdbc:postgresql://localhost:5432/postgres";
             con=DriverManager.getConnection(conninfo,"allii","12345");

             input = new FileInputStream(new File("ADP.jrxml"));
             jd = JRXmlLoader.load(input);
             jr = JasperCompileManager.compileReport(jd);
             jp = JasperFillManager.fillReport(jr,null,con);
             output = new FileOutputStream(new File("A_D_P.pdf"));
             JasperExportManager.exportReportToPdfStream(jp,output);
             
 //            JFrame frame = new JFrame("Report_1");
//             frame.getContentPane().add(new JRViewer(jp));
//             frame.pack();
//             frame.setVisible(true);
             
             output.close();
             input.close();
             con.close();
             JOptionPane.showMessageDialog(null, "Success !");

        }catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex.toString());
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed


    
    


//_______________________________________________________________________________________
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
